### ISSUE TITLE
Issues with new message notifications and deleting messages

### ISSUE THREAD

**Issue by pquesinb** [mt-mods/mail#45]
Hi,

Great mod, love the changes!  But one of the recent commits (I think it was the big one - commit b3e0c158f7a81731ec342d9161c2ffa4ecb438c0 but I'm not completely certain), appears to have broken email notifications.  If I get a new message while I am online, I see the notification in the chat (but no yellow envelope in the center of the screen as before).  But there is no notification of new messages if a new message is received while I am offline - when I re-join, I have to open my mail to see if any new messages were received.

Also, I sent myself a test message to verify this behavior and discovered that I couldn't delete it, it remains in my inbox.

Sever is 5.6.1 - if there is any additional information that I can provide to help in troubleshooting, please let me know.  I see no error messages related to any of this activity in the standard server log.

Many thanks for all of your hard work on this mod.

\- Phil

**Comment by Athozus** [comment]
> Hi,
> 
> Great mod, love the changes!

Thanks for that !

> But one of the recent commits (I think it was the big one - commit [b3e0c15](https://github.com/mt-mods/mail/commit/b3e0c158f7a81731ec342d9161c2ffa4ecb438c0) but I'm not completely certain), appears to have broken email notifications. If I get a new message while I am online, I see the notification in the chat (but no yellow envelope in the center of the screen as before). But there is no notification of new messages if a new message is received while I am offline - when I re-join, I have to open my mail to see if any new messages were received.

This is o_O, I will fix it, thanks for reporting that.

> Also, I sent myself a test message to verify this behavior and discovered that I couldn't delete it, it remains in my inbox.

Fixed by #36, thx for reporting it. Please update the mod, 1.0.1 was published earlier in the day.

> Sever is 5.6.1 - if there is any additional information that I can provide to help in troubleshooting, please let me know. I see no error messages related to any of this activity in the standard server log.

It's ok, but it will be probably trivial =)

> Many thanks for all of your hard work on this mod.

Many thanks to you for that words =)

Athozus.

**Comment by pquesinb** [comment]
Athozus,

Thanks for fixes!  An issue still remains with this though, the new message status only updates when the player joins so I'm guessing that the status needs to be rechecked/updated whenever a message is read/deleted, etc.

To reproduce:
Create new message to yourself - new message notification appears in chat and in game screen/HUD.
Read and/or delete message - new message notification envelope still appears as before.
Log out and re-join - new message status properly updated - notification no longer appears.

Also, a request: would it be possible to include a config option to change the sort order?  Previous behavior sorted in descending date order (ascending message age order - new messages at top), while new behavior puts new messages at the bottom.  I strongly prefer the old sort-order but some folks might like the new.

Again, many thanks!  It's really great not having to BCC yourself to be able to refer back to messages you've sent.

\- Phil

**Comment by Athozus** [comment]
Thanks for replying !

I will look into the HUD bug, thanks for reporting.

For the filters, it's already planned #39, sorry it's due to new storage sometimes it is added at first sometimes not, but I wouldn't blame @BuckarooBanzay for that as it works was really good.

Thanks anyway.
